######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 29 16:35:40 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FileInformation.h
SOURCES += fileInformation.cpp main.cpp
